function [ out_similarity ] = Crossover( similarity, RMSE, num_users )
% This function is used to generate a new similarity matrix from two existing matrix using the weighted average method, 
% and RMSE is the weight
% input:similarity contains 20 matrix of similarity
%       RMSE is the 20 Root Means Square Error of that 20 similarity
% output:out_similarity is the outcome similarity generated by every 2
%       similarity.

num = 10; % 10 similarity matrix will be returned;
out_similarity = zeros(num, num_users, num_users);
for i = 1 : num
     out_similarity(i, :, :) = (RMSE(2*i-1)*reshape(similarity(2*i-1,:,:),num_users,num_users) + RMSE(2*i)*reshape(similarity(2*i,:,:),num_users,num_users)) / (RMSE(2*i-1) + RMSE(2*i));
end

end